from gym_k8s_real.envs.k8s_env_discrete_state_discrete_action import K8sEnvDiscreteStateDiscreteAction
from gym_k8s_real.envs.k8s_env_discrete_state_five_action import K8sEnvDiscreteStateFiveAction
# from gym_k8s_real.envs.k8s_env_discrete_state_discrete_action_15Rres import K8sEnvDiscreteStateDiscreteAction15Rres
from gym_k8s_real.envs.k8s_env_discrete_state_discrete_action_20Rres import K8sEnvDiscreteStateDiscreteAction20Rres
from gym_k8s_real.envs.k8s_env_DQN import K8sEnvDQN