apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy2
  name: proxy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy2
  strategy: {}
  template:
    metadata:
      labels:
        app: proxy2
    spec:
      containers:
        - image: jamilakassem/proxy-chaining_cli
          name: proxy2
          command: ["./socksx"]
          args: ["-c", "socks6://145.100.135.52:30021", "-c", "socks6://145.100.135.16:30011"]
          ports:
            - containerPort: 1080
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
      nodeName: jk-04
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy2
  name: proxy2
spec:
  type: NodePort
  selector:
    app: proxy2
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30007
      protocol: TCP
