apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy1
  name: proxy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy1
  strategy: {}
  template:
    metadata:
      labels:
        app: proxy1
    spec:
      containers:
        - image: jamilakassem/proxy-chaining_cli
          name: proxy1
          command: ["./socksx"]
          args: ["-c","socks6://10.0.0.79:1080","-c","socks6://10.0.0.7:1080","-c","socks6://10.0.0.217:1080"]
          ports:
            - containerPort: 1080
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 100m
      nodeName: jk-02 
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy1
  name: proxy1
spec:
  type: NodePort
  selector:
    app: proxy1
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30007
      protocol: TCP
